/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_fz_jni_JniSimple */

#ifndef _Included_com_fz_jni_JniSimple
#define _Included_com_fz_jni_JniSimple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fz_jni_JniSimple
 * Method:    getSingnaturePassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fz_jni_JniSimple_getSingnaturePassword
        (JNIEnv *, jobject);

/*
 * Class:     com_fz_jni_JniSimple
 * Method:    changeName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fz_jni_JniSimple_changeName
        (JNIEnv *, jobject);

/*
 * Class:     com_fz_jni_JniSimple
 * Method:    callAddMathod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fz_jni_JniSimple_callAddMathod
        (JNIEnv *, jobject);

/*
 * Class:     com_fz_jni_JniSimple
 * Method:    changeAge
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fz_jni_JniSimple_changeAge
        (JNIEnv *, jclass);

/*
 * Class:     com_fz_jni_JniSimple
 * Method:    callStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fz_jni_JniSimple_callStaticMethod
        (JNIEnv *, jclass);

/*
 * Class:     com_fz_jni_JniSimple
 * Method:    createPoint
 * Signature: ()Lcom/fz/jni/Point;
 */
JNIEXPORT jobject JNICALL Java_com_fz_jni_JniSimple_createPoint
        (JNIEnv *, jclass);

/*
 * Class:     com_fz_jni_JniSimple
 * Method:    sort
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_fz_jni_JniSimple_sort
        (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_fz_jni_JniSimple
 * Method:    exception
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fz_jni_JniSimple_exception
        (JNIEnv *, jclass);

/*
 * Class:     com_fz_jni_JniSimple
 * Method:    initStaticCache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fz_jni_JniSimple_initStaticCache
        (JNIEnv *, jclass);

/*
 * Class:     com_fz_jni_JniSimple
 * Method:    staticLocalCache
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fz_jni_JniSimple_staticLocalCache
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fz_jni_JniSimple
 * Method:    delteGlobalRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fz_jni_JniSimple_delteGlobalRef
        (JNIEnv *, jclass);

/*
 * Class:     com_fz_jni_JniSimple
 * Method:    getGlobalRef
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fz_jni_JniSimple_getGlobalRef
        (JNIEnv *, jclass);

/*
 * Class:     com_fz_jni_JniSimple
 * Method:    saveGlobalRef
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fz_jni_JniSimple_saveGlobalRef
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fz_jni_JniSimple
 * Method:    localRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fz_jni_JniSimple_localRef
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
